### ISSUE TITLE
Create a system of project-related badges for member profiles

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#25] opened 2020-06-21 02:18 UTC
Basically, the goal here is to "gamify" projects a bit. We need to define these badges a bit more, determine how they relate to projects, how they're tracked, etc.

Probably requires moving member info to something that looks more like an actual database, rather than the current flat-file system.

**Comment by tilnow** [comment] 2020-07-22 13:11
is this or is this not possibly a duplicate of #32 or, maybe again we want to store this information on a stand-alone database

**Comment by necopinus** [comment] 2020-07-24 01:56
I think this is probably not a well-defined task, and for the moment is probably close enough to #32 to be considered a dupe.

**Closed as completed** 2020-07-24 01:56 UTC
Labels: enhancement, help wanted
